---
title: "R Notebook"
output: html_notebook
---

This notebook will explore text reuse in Indain treaties at the paragraph level. 
```{r}
library(rvest)
library(magrittr)
library(tidyverse)
library(stringr)
library(pbapply)
library(parallel)
library(textreuse)

```


###Creating the Corpus with Minhashes

```{r createcorpus2, cache=TRUE}
treaties <- readRDS("parsed_treaties.rds")
minhash <- minhash_generator(n = 40, seed = 3552)

docs <- treaties$body
names(docs) <- basename(treaties$file)

corpus <- TextReuseCorpus(text = docs, meta = list(treaties$title), 
                          tokenizer = tokenize_ngrams, n = 5,
                          minhash_func = minhash, keep_tokens = TRUE,
                          progress = FALSE)

```



```{r}

lsh_threshold(h = 40, b = 20)

buckets <- lsh(corpus, bands = 20, progress = FALSE)
```

###Finding Candidates
```{r}
#matches <- lsh_query(buckets, "19000630400")
#matches
candidates <- lsh_candidates(buckets)
```

### Comparing Candidates
```{r}

similarities <-lsh_compare(candidates, corpus, jaccard_similarity)
```

Histogram of similarities
```{r} 
hist(similarities$score, breaks = 100) 
```


