---
title: "R Notebook"
output: html_notebook
---
#Digitally Analyzing the Uneven Ground: Language Borrowing in Indian Treaties

*How smooth must be the language of the whites, when they can make right look like wrong, and wrong like right.*
*--Blackhawk*

	Word choice and the functioning of language itself has become an important sub-field within indigenous history. As Patricia Limerick has noted, “the process of invasion, conquest, and colonization was the kind of activity that provoked a shiftiness in verbal behavior.”  As Blackhawk’s quote demonstrates, modern scholars were not the first individuals to recognize words as tools of settler colonialism. Jean M. O’Brien’s Firsting and Lasting: Writing Indians Out of Existence in New England and James Joseph Buss’ Winning the West with Words: Language and Conquest in the Lower Great Lakes demonstrate how non-indigenous authors, politicians, and historians used language to exterminate Indians in the collective American consciousness even if they failed to do so in reality. Still, the written words that most impact the lives of Native Americans are contained within treaties. 
	Numerous scholars including David Wilkins, Vine Deloria, Jr., and K. Tsianina Lomawaima have examined the importance of treaties to federal Indian policy. Other scholars such as Chantal Norrgard, Patricia Pierce Erikson, and Jean Dennison have focused on the impact of specific treaties on particular nations. These analyses trace the implications of words to the critical issues of tribal sovereignty and fishing, whaling, hunting, mineral, and gathering rights. Despite the flourishing of this New Tribal History, the examination of treaties as a single corpus has yet to be undertaken. This essay explores the content and connections between treaties using the methods of digital history. It argues that treaty authors frequently borrowed both content and language from previous documents but only rarely did this borrowing occur over long periods of time or across geographic regions. Most treaties borrowed from their immediate temporal predecessors and geographic neighbors.
	
##1. Research questions and methodology
	This research project was framed around several specific questions: 
	
*To what extent did treaties adhere to a standard structure or form?
*Were there specific treaties that subsequent authors and negotiators modeled their agreements after in terms of language? 
*If borrowing did occur, what portions of previous treaties did authors or negotiators borrow and why?
*How did time and geography influence the content and language of treaties? 

As with any historical research project, I chose the methods and theoretical frameworks for their ability to answer and/or explore these aforementioned research questions. Central to answering these questions is the method of digitally detecting text reuse or borrowing. In many ways this approach works similarly to plagiarism detection software in that a computer program scans a series of documents and calculates the similarity between them. In this case, the computer is not identifying plagiarism but language borrowing. This is not the first study to employ such an approach. Ryan Cordell successfully used the method of digitally detecting text reuse to trace the reprinting and circulation of articles by a network of 19th century newspapers. Kellen Funk and Lincoln Mullen also used this approach to trace the state to state borrowing of legal code within American law. It is from this latter study that this essay draws most of its methodology.
	To acquire the text of the treaties in digital format, I scraped the text of the documents from Oklahoma State’s Kappler Project website, where they host the 388 digital transcriptions of the treaties contained in Charles J. Kappler’s Indian Affairs: Laws and Treaties. This approach eliminated the issue that many digital history projects have concerning the quality of Optical Character Recognition (turning scanned images into digital text) because the online text was manually transcribed. After acquiring the treaties, I massaged them into a format conducive to answering the research questions and compatible with R, the programming software that was used to analyze the texts. 
	In order to compute similarity scores that went beyond a document to document comparison, I split the body of the treaties apart and turned them into their own separate files. This approach allowed for a paragraph to paragraph computation of similarity and allowed for the documents to be visually displayed in a network graph both at the document and paragraph level.
	Using Lincoln Mullen’s "textreuse: Detect Text Reuse and Document Similarity" package for R, I computed the similarity of the documents and turned the results into the visualizations that appear in this essay. In addition to the network graphs, I also clustered the documents using affinity propagation clustering in order to identify clusters of closely related texts. This process helped detect groups of texts that borrowed from the same “exemplar” document. The findings, questions, and anomalies that this process raised will be addressed in the second and third sections of this essay.

##2. A macro view of the uneven ground
In their study of Indian sovereignty and American law, David Watkins and K. Tsianina Lomawaima describe federal Indian policy as an “uneven ground” characterized by “inconstancy, indeterminacy, and variability” (6). They observed that “Indian policy has not proceeded along some smooth racetrack, but has pitched and bumped over the rutted tracks that the conflicting interests of tribes, states, federal agencies, railroads, energy and industrial barons, homesteaders, tourists, and casual visitors have carved across Indian Country” (6). This section examines just one layer of this uneven ground, Indian treaties. 
From a macro perspective, the nearly 400 different Indian treaties of the uneven ground share many commonalities. In addition to their shared content (land, gifts, payments, protections, trade), they generally followed similar language borrowing patterns. While text reuse is only one indicator of the connections and influences previous treaties had upon subsequent agreements, it is particularly useful in this case. Given the extent to which most treaties contained a narrow set of topics, it can be difficult to say with any certainty which treaties served as templates or models for other treaties (and to a certain extent they all did). The benefit of using digital methods to detect text reuse is that it can identify language pattern similarities that would be nearly impossible to detect using close reading. Thus, it is possible to see what early 19th century treaty someone used as a template in the 1850s. For example, the following two paragraphs are matches returned by the computer program. The first text below is taken from an 1804 treaty with the Sauk and Foxes (sau0074-00011). The second text is taken from an 1853 treaty with the Umpqua Cow Creek Band (ump0606-00012 ). 

>“Lest the friendship which is now established between the United States and the said Indian tribes should be interrupted by the misconduct of individuals, it is hereby agreed that for injuries done by individuals no private revenge or retaliation shall take place, but, instead thereof, complaints shall be made by the party injured to the other—by the said tribes or either of them to the superintendent of Indian affairs or one of his deputies, and by the superintendent or other person appointed by the President, to the chiefs of the said tribes. And it shall be the duty of the said chiefs upon complaint being made as aforesaid to deliver up the person or persons against whom the complaint is made, to the end that he or they  may be punished agreeably to the laws of the state or territory where the offence may have been committed; and in like manner if any robbery, violence or murder shall be committed on any Indian or Indians belonging to the said tribes or either of them,  the person or persons so offending shall be tried, and if found guilty, punished in the like manner as if the injury had been  done to a white man. And it is further agreed, that the chiefs of the said tribes shall, to the utmost of their power exert themselves to recover horses or other property which may be stolen from any citizen or citizens of the United States by any individual or individuals of their tribes….”


>“That the friendship which is now established between the United States and the Cow Creek band of Indians, shall not be interrupted  by the misconduct of individuals, it is hereby agreed that for injuries done, no private revenge or retaliation shall take place; but instead thereof complaint shall be made by the party injured to the Indian  agent; and it shall be the duty of the chiefs of said band of Indians, upon complaint being made as aforesaid, to deliver up the person against whom the complaint is made, to the end that he may be punished, agreeably to the laws of the United States; and in like manner if any violation, robbery, or murder shall be committed on any Indian belonging to said band, the person so offending shall be tried, and if found guilty, shall be punished according to the laws of the United States. And it is further agreed that the chiefs shall, to the utmost of their ability, exert themselves to recover horses or other property   which has or may hereafter be stolen from any citizen of the United States, by any individual of said tribe….”
The latter treaty clearly used the former as a template for the structure and content of the treaty. As can be seen some updates were made to the 1853 treaty as the phrase, “punished in the like manner as if the injury had been done to a white man” became “be punished according to the laws of the United States.” This type of borrowing occurred frequently, and it followed a strong trend. 

	In most cases, treaties only borrowed from their immediate temporal predecessors and geographic neighbors. Very rarely did this borrowing occur over long periods of time or across geographic regions. The histogram below charts the time span of treaty borrowing. For example, if a paragraph from treaty_a was written in 1848 and a paragraph from treaty_b was written in 1855, then the span is 7 years. 
	
	
HISTOGRAM
The vast majority (89%) of the treaty borrowing occurred within a two year span. This number is slightly skewed due to the fact that commissioners often composed, within a few days or months, a cluster of treaties dealing with a group of nations or bands. For example, Brigadier-general Henry Atkinson and Indian agent Major Benjamin O'Fallon composed several treaties in 1825 with the Arikara, Makah, Belantse-Etoa (Minitaree), Cheyenne, Crow, Ponca, Pawnee, and Mandan nations in addition to agreements with several bands of the Sioux. All of these treaties were composed within a few months and share over a dozen paragraphs. The text reuse detection model still includes these treaties as examples of borrowing. While this cluster of treaties does not indicate what texts Atkinson and O’Fallen used as models, it does highlight another general characteristic of Indian treaties, contextual composition. 
Rather than having a governmentally mandated master document detailing the necessary form and content of a treaty, the commissioners molded treaties to correspond to the unique situational circumstances of the uneven ground.  The following network graph displays the borrowing that occurred between treaties. The width or thickness of the connection edges or lines is a summation of the total number of paragraphs shared between two treaties. 
NETWORK GRAPH
As the network graph indicates, there was very limited borrowing across time. Most of these clusters of treaties contain only one or two colors (corresponding to decades). Also visible are several isolated clusters of treaties that represent the practice of treaty borrowing mentioned above where a commissioner composed several treaties within a short span of time. For example, the following network graph shows the borrowing between the different treaties negotiated with the Sioux bands in 1865.
Sioux_1865
This commissioner specific language also limited borrowing geographically as the commissioners rarely veered from their groove in the uneven ground. Most often treaties borrowed from their geographic neighbors or from previous agreements with the same nation(s). Even when treaty authors and negotiators used a particular nation’s previous agreements as models, they chose recent treaties. The treaties concerning the Delaware illustrate this point. Between the American Revolution and the Civil War the Delaware nation migrated (often by force) from Pennsylvania to lands west of the Mississippi River in Kansas and Oklahoma. During this time period they signed numerous treaties both as sole signatories and joint signatories. However, when the authors and negotiators of these treaties did look to previous treaties with the Delaware to borrow language, they did not use treaties signed in different geographic regions. The following network graph displays the treaties signed by the Delaware as sole or primary signatories. 
Delaware Graph
As the network shows, the few Delaware treaties that did borrow from previous Delaware treaties did not span a great deal of time or, in the case of the Delaware, geography. The three detected borrowings occurred over time spans of one, six, and eleven years. The treaties signed by the Delaware in Ohio and Indiana from the 1770s-1810s did not serve as language templates for treaties signed west of the Mississippi. There are only a few examples of treaties that borrowed language from agreements in different geographical regions.
3. A micro view of selected examples
While the general trend for language borrowing among treaties was limited by time and geography, there were some exceptions to this rule. The most obvious example is the 1846 treaty signed by the Comanche, Aionai, Andarko, and Caddo nations. Unlike most treaties, the negotiators/authors of this treaty looked to the distant past for inspiration. The following two texts are taken from the 1789 Treaty of Fort Harmar signed in present day Ohio with several different Indian nations and the aforementioned 1846 treaty negotiated with the Comanche and other nations near modern day Texas respectively. (wya0018-00011)
“It is agreed that if any Indian or Indians of the nations before mentioned, shall commit a murder or robbery on any of the citizens of the United States, the nation or tribe to which the offender belongs,          on complaint being made, shall deliver up the person or persons complained of, at the nearest post of the United States; to  the end that he or they may be tried, and if found guilty, punished according to the laws established in the territory of  the United States north-west of the river Ohio, for the punishment of such offences, if the same shall have been committed within the said territory; or according to the laws of the State where the offence may have been committed, if the same has          happened in any of the United States. In like manner, if any subject or citizen of the United States shall commit murder or robbery on any Indian or…”       
“It is agreed that, if any Indians shall commit a murder or robbery on any citizen of the United States, the tribe or nation to which the offender belongs shall deliver up the person or persons so complained of, on complaint being made to their chief, to the nearest post of the United States, to the end that he or they may be tried, and, if found guilty, punished, according to the law of the State or Territory where such offence may have been committed. In like manner, if any subject or citizen of the United States shall commit murder or robbery on any Indian or Indians of the said tribes or nations, upon complaint thereof to the agent residing near them, he or they shall be arrested, tried, and punished according to the law of the State or Territory where such offence may have been committed.”
The latter text obviously borrowed the language from the treaty written fifty-seven years before. In addition to the 1789 Treaty of Fort Harmar, the treaty also borrowed language from the 1790 treaty with the Creek, and the 1795 Treaty of Greenville (Ohio). The following network graph shows the sub-group of treaty borrowing containing the 1846 treaty (the only red dot or treaty from the 1840s). 
G2[[3]]
Answering why this treaty looked to the distant past is a bit murky. 
	There are two plausible reasons for explaining the long term language borrowing in the 1846 treaty with the Comanche. The first possibility is that the language borrowing can be attributed to the background of the commissioners, Pierce Mason Butler (1798 – 1847) and M. G. Lewis. Pierce Butler was a former governor of South Carolina (1836-1838) who became an Indian agent following his brief governorship, a post which he held until his death during the Mexican American War. Butler had several important familial connections including his father, William Butler. The elder Butler was a politician who also served in numerous military campaigns against Indians during his thirty-nine year military career (1775–1814). It is possible that the younger Butler looked to his father’s career when he was tasked with serving as an Indian agent. A more likely explanation is that Butler and Lewis looked to the past because of the specific historical milieu of Comancheria, the Comanche homeland, in the 1840s.
Comancheria during the 1840s was controlled by the powerful Comanche Empire. The economic engine of this empire was a system of raiding and trading. The Comanche and their allies would raid the villages of the encroaching American and Mexican settlers and then sell their acquisitions to other Indian nations or American/Mexican traders. In his book Comanche Empire, Pekka Hamalainen noted that the Comanche “saw the Spanish and Mexican ranches, missions, and settlements as an economic resource that was to be exploited rather than destroyed” (245).  In effect, “Texas spent three-quarters of a century as a carefully managed livestock repository for Comancheria” (245).  While the Comanche had a different objective, their system of intensive raiding shared many similarities with that of the Ohio Indians in the 1780s and 1790s. 
During the 1780s and 1790s what would become the state of Ohio was controlled by an Indian coalition that included members of the Wyandot, Shawnee, Delaware, Mingo, and other nations. This coalition attempted to stop American settlement north of the Ohio River by raiding frontier settlements and frequently killing trespassers. Rather than treating the American settlements as a livestock repository, the Indian coalition of Ohio used raiding as an effective intimidation weapon. This violent frontier forced the fledgling American federal government to launch several unsuccessful military campaigns to pacify the region. It would not be until the Treaty of Fort Greenville in 1795 that the majority of the raiding would stop. Perhaps Butler and Lewis saw enough parallels between these two situations that they decided to model their 1846 agreement off of treaties signed to resolve similar situations. This assumption may be impossible to prove without a written statement from the commissioners, but it is telling that the paragraphs that they chose to borrow contained language concerning raiding. 
In addition to the paragraph from the 1787 Treaty of Fort Harmar discussed earlier, the 1846 Comanche treaty also borrowed the following passage.
1787 Treaty of Fort Harmar: 
“And whereas the practice of stealing horses has prevailed very much, to the great disquiet of the citizens of the United States, and if persisted in, cannot fail to involve both the United States of America and the Indians in endless animosity, it is agreed that it shall be put an entire stop to on both sides; nevertheless, should some individuals, in defiance of this agreement, and of the laws provided against such offences, continue to make depredations of that nature, the person convicted thereof shall be punished  with the utmost severity the laws of the respective states, or territory of the United States north-west of the Ohio, where the offence may have been committed, will admit of: And all horses so stolen, either by the Indians from the citizens or subjects of the United States, or by the citizens or subjects of the United States from any of the Indian nations, may be reclaimed, into whose possession soever they may have passed, and, upon due proof, shall be restored; any sales in market overt, notwithstanding. And the civil magistrates in the United States respectively, and in the territory of the United States north-west of the Ohio, shall give all necessary aid and protection to Indians claiming such stolen horses.”
1846 Comanche Treaty:
“The practice of stealing horses has prevailed very much to the great disquiet of the citizens of the United States, and, if persisted in, cannot fail to involve both the United States and the Indians in endless strife. It is therefore agreed that it shall be put an entire stop to on both sides. Nevertheless, should bad men, in defiance of this agreement, continue to make depredations of that nature, the person convicted thereof shall be punished with the utmost severity, according to the laws of the State or Territory where the offence may have been committed: and all horses so stolen, either by the Indians from the citizens of the United States or by the citizens of the United States from any of the said tribes or nations, into whose possession soever they may have passed, upon due proof of rightful ownership, shall be restored; and the chiefs of said tribes or nations shall give all necessary aid and protection to citizens of the United States in reclaiming and recovering such stolen horses; and the civil magistrates of the United States, respectively, shall give all necessary aid and protection to Indians in claiming and recovering such stolen horses.”
```{r}
readRDS("cluster_df_years.rds")
hist(abs(cluster_df_years$borrow_span),
main="Histogram of Paragraph Borrowing Across Time", 
     xlab="Difference in time between exemplar and borrower in years\n *The first column (1-2 years) = 1113", 
     border="black", 
     col="green",
     xlim=c(0,60),
     ylim= c(0,100),
     las=1,
     breaks=50)
```

The passage is nearly borrowed verbatim, but is surprisingly appropriate for the situation in Comancheria. The problem of Comanche raiding was not the only issue that Butler and Lewis looked to the past to solve. 

In addition to the practice of raiding, the two situations also shared another commonality. Both regions lacked a substantial and stable population of American settlers. In each situation, the American government was attempting to suppress violence occurring on its ever expanding frontier. In both situations, the respective Indian nations comprised a majority of the population and the United States sought to ensure the safe travel and commerce of its traders by establishing a licensing system. This particular dynamic is also reflected in a passage borrowed from the 1795 Treaty of Fort Greenville.

The 1795 Treaty of Fort Greenville:
>“…their property, as shall be duly licensed to reside among them for the purpose of trade, and to their agents and servants; but no person shall be permitted to reside at any of their towns or hunting camps as a trader, who is not furnished with a license for that purpose, under the hand and seal of the superintendent of the department north-west of the Ohio, or such other person as the President of the United States shall authorize to grant such licenses; to the end, that the said Indians may not be imposed on in their trade. And if any licensed trader shall abuse his privilege by unfair dealing, upon complaint and proof thereof, his license shall be taken from him, and he shall be further punished according to the laws of the United States. And if any person shall intrude himself as a trader, without such license, the said Indians shall take and bring him before the superintendent or his deputy, to be dealt with according to law.” 

The 1846 Comanche Treaty:
“…their property, as shall be duly licensed to reside among them for the purpose of trade and intercourse, and to their agents and servants, but no person shall be permitted to reside among them as a trader who is not furnished with a license for that purpose, under the hand and seal of the superintendent to be appointed by the President of the United States or such other person as the President shall authorize to grant such licenses, to the end that said Indians may not be imposed on in their trade; and if any licensed trader shall abuse his privilege by unfair dealing, upon complaint by the chiefs to their agents and proof thereof, his license shall be taken from him, and he shall be further punished according to the laws of the United States; and if any person shall intrude himself as a trader without such license, upon complaint he shall be dealt with according to law.”
Once again, the authors of the 1846 Comanche Treaty looked to an 18th century treaty to address a contemporary problem. 
Conclusion
Examining the nearly four hundred Indian treaties using digital methods revealed a network of language borrowing. While the practice was widespread, it was confined geographically and temporally. In certain cases such as the 1846 Comanche Treaty, borrowing across decades and geographic regions did take place in order to address similar contemporary issues. While highlighting the presence of borrowing, further investigation is needed to understand why it occurred. Likewise the treaties that did not borrow language from other agreements should be interrogated. What was unique about these situations that the treaty authors did not borrow passages? Was this the result of indigenous persons exercising influence upon the commissioners? Were the individuals who negotiated the treaties without borrowing neophytes? These are as of yet unanswered questions that will serve as starting points for further research. 

Osage (borrowed from previous Osage over years) 



