---
title: "R Notebook"
output: html_notebook
---
#Indian Treaty Corpus Creation
This notebook details the process that I used to create my corpus of Indian treaties. Before I ran any of the code below, I used Wget to scrape the treaties from online (http://digital.library.okstate.edu/kappler/Vol2/Toc.htm). 

```{r}
library(rvest)
library(magrittr)
library(tidyverse)
library(stringr)
library(pbapply)
library(parallel)
```
I then loaded the package rvest in order to parse the htm documents created using Wget.
```{r}
test_treaty <- read_html("C:/Users/Joshua/Documents/wget_treaties/digital.library.okstate.edu/kappler/Vol2/treaties/apa0598.htm")

file <- "C:/Users/Joshua/Documents/wget_treaties/digital.library.okstate.edu/kappler/Vol2/treaties/apa0598.htm"
```

```{r}
title <- test_treaty %>%
  html_nodes("h4 center") %>%
  html_text()

title <- title[c(1)] 


treaty_descpription <- test_treaty %>%
  html_nodes("p i") %>%
  html_text() %>% 
  str_c(collapse = " ")

treaty_descpription

body <- test_treaty %>%
  html_nodes("body p") %>%
  html_text() %>% 
  str_c(collapse = " ")

body


```

```{r}
parser <- function(file) {
  message("Parsing ", file)
  trt <- read_html(file) 
   
  title <- trt %>%
  html_nodes("h4 center") %>%
  html_text()
  
  title <- title[1]

  treaty_descpription <- trt %>%
  html_nodes("p i") %>%
  html_text()%>%
  str_c(collapse= " ")


  body <- trt %>%
  html_nodes("body p") %>%
  html_text() %>%
  str_c(collapse= "\n\n")
  
  data_frame(file = file, title = title, body = body,
             description = treaty_descpription)
  
}
```

```{r}
# file_to_df <- failwith(NULL, parser)

treaty_filenames <- list.files("C:/Users/Joshua/Documents/wget_treaties/digital.library.okstate.edu/kappler/Vol2/treaties/",
                               pattern = "\\.htm",
                               full.names = TRUE)

parsed <- map_df(treaty_filenames, parser)

```
```{r}

```



